//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Codigo_Documento
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FechaDoc { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Usuario")]
        [EmailAddress (ErrorMessage = "Debe ser un correo valido")]
        [StringLength(40, ErrorMessage = "Solo puede contener 40 digitos.")]
        public string UserCorreo { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Departamento Origen")]
        public int Departamento_Origen { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [Display(Name = "Departamento Destino")]
        public int Departamento_Destino { get; set; }
        public string Secuencia { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Departamento Departamento1 { get; set; }
    }
}
